### PR TITLE
Better cache for roles and permissions

### PR DESCRIPTION
**Pull request by hamid-a**
In this PR I changed cachedPermissions and cachedRoles functions for better performance and preventing more requests to the database.

### CODE REVIEW

**Comment by klaravel** [comment]
Hey @hamid-a,

Thanks for contribution and nice concept.

I was wondering that do you thing with that code we need to clear that variable if object change how current code clear cache?

[https://github.com/hamid-a/ntrust/blob/7f1d69e353f91c5b9decc21a202d3cf5ce6c4672/src/Ntrust/Traits/NtrustRoleTrait.php#L63-L96](url)
 
Same on other files?

**Comment by hamid-a** [comment]
@klaravel 
Thanks for your response.
You are right.
I'm forget it.
It's now fixed.

**Comment by klaravel** [comment]
@hamid-a 

That code won't work because when cache store as individual user's roles.

Because of static. It always show first used cached user's roles.

**Comment by hamid-a** [comment]
So we can push it into array with associative id key

```
public function cachedPermissions()
{
    $rolePrimaryKey = $this->primaryKey;
    $roleKey = $this->$rolePrimaryKey;
    $cacheKey = 'ntrust_permissions_for_role_'.$roleKey;
    if (isset(self::$permissions[$roleKey])) {`
        return self::$permissions[$roleKey];
    } else if (Cache::getStore() instanceof TaggableStore) {
        self::$permissions[$roleKey] = Cache::tags(Config::get('ntrust.profiles.' . self::$roleProfile . '.permission_role_table'))->remember($cacheKey, Config::get('cache.ttl', 1440), function () {
            return $this->perms()->get();
        });
        return self::$permissions[$roleKey];
    } else {
        self::$permissions[$roleKey] = $this->perms()->get();
        return self::$permissions[$roleKey];
    }
}
```

**Pull request merged**
